name: Generar PDF de Tareas

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean

permissions:
  contents: write # Permiso de escritura para `GITHUB_TOKEN`

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python y bibliotecas
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install -r scripts/requirements.txt

      - name: Ejecutar script para generar PDF
        run: |
          python3 scripts/generar_pdf.py

      - name: Subir artefactos
        uses: actions/upload-artifact@v3
        with:
          name: pdf-tareas
          path: pdf/

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Checkout de la rama
        run: |
          git checkout master  # Cambia a 'main' si tu repositorio usa esa rama

      - name: Hacer commit y push de los archivos PDF
        run: |
          git add pdf/
          git commit -m "Agregar archivos PDF generados"
          git push origin master  # Cambia a 'main' si es necesario
