name: Generar PDF de Tareas

on:
  push:
    branches:
      - main

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de Latex y Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive pandoc

      - name: Instalar Python y bibliotecas
        run: |
          sudo apt-get install -y python3 python3-pip
          pip3 install fpdf

      - name: Ejecutar script para generar PDF
        run: |
          python3 scripts/generar_pdf.py
